name: 1.19.2 Auto Build

on:
  push:
    branches:
      - '1.19.2'
    paths:
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build publish

      - name: mc-publish-fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: gzevkJbM
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 871522
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc|dev-shadow)).jar

          name: Photon Editor 1.0.3-fabric
          version: mc1.19.2-fabric-1.0.3
          version-type: beta
          changelog-file: CHANGELOG.*

          loaders: |
            fabric
          game-versions: |
            1.19.2
          game-version-filter: none
          dependencies: |
            ldlib@1.0.7(required){modrinth:B1CBVXHX}{curseforge:626676}
          java: |
            17
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: mc-publish-forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: gzevkJbM
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 871522
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            forge/build/libs/!(*-@(dev|sources|javadoc|dev-shadow)).jar

          name: Photon Editor 1.0.3-forge
          version: mc1.19.2-forge-1.0.3
          version-type: beta
          changelog-file: CHANGELOG.*

          loaders: |
            forge
          game-versions: |
            1.19.2
          game-version-filter: none
          dependencies: |
            ldlib@1.0.7(required){modrinth:B1CBVXHX}{curseforge:626676}
          java: |
            17
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail